Update the local simulator API
qc-design/plaquette pull request #45
Opened 2023-09-25 13:11 UTC by antalszava

With https://github.com/qc-design/plaquette/pull/3 a new Device API was introduced. 

The changes didn't resolve the slight mismatch between the API that the local simulators used internally and the API that the `Device` started using. The local simulators had to be created by provided a circuit to later run, whereas a `Device` could be created without a circuit. The circuit was only required when calling `Device.run`.

This PR updates the simulators so that:
* The circuit argument is moved from the `__init__` method of the `CircuitSimulator` and `StimSimulator` classes to their `run` method;
* The `process_results` method is removed and only the `get_sample` method is kept.

2023-09-27 08:39 UTC, massarom requested changes
Some small comments that IMO should be addressed, but the main bulk of the PR is good to go.

2023-09-27 08:39 UTC, massarom commented on src/plaquette/device/_stimsim.py
> +    circ: plaq_circuit.Circuit | None,
It makes no sense that the circuit could be `None` here because this function would not work at all with that value. Why this change? (also applies to the edit below, around the big `for` loop)

2023-09-27 08:39 UTC, massarom commented on src/plaquette/device/_stimsim.py
> +
```suggestion
        self.circ: plaq_circuit.Circuit | None = None
        self.stim_circ: stim.Circuit | None = None
        self.meas_is_erasure = np.ndarray | None = None
        self.stim_sampler: stim.CompiledMeasurementSampler | None = None

```

Always init all instance variables in the init.

2023-09-27 08:39 UTC, massarom commented on src/plaquette/device/__init__.py
>          return self._backend.run(circuit, shots=shots)
Since we're removing inconsistencies among the simulators APIs, is this difference still necessary? Shots could be also simply set as `shots=1` in the local simulators and a warning/error be given if a number different than 1 is selected by the user. This would remove the last (AFAICS) API difference in how devices are handled. (same goes for the `after_reset` parameter)

2023-09-27 11:16 UTC, antalszava commented on src/plaquette/device/_circuitsim.py
> +        self.circ = None
Oh, I see thank you! Should we have a TODO GitHub issue to change to the preferred format in existing files?

2023-09-27 11:24 UTC, antalszava commented on src/plaquette/device/_stimsim.py
> +
* My thought here was that since we're calling `self.reset`, we could break the conventional initialization of instance variables in `__init__`. If we do want to do that nonetheless, there's going to be a bit of a duplication between `__init__` and `reset`, are we okay with that?
* Setting `self.circ` to `None` ends up bringing up an issue with MyPy:
```
src/plaquette/device/_stimsim.py:120: error: Incompatible types in assignment (expression has type "None", variable has type "Circuit")  [assignment]
```
Frankly, I'm not sure where this is coming from because it persists even if I remove any uses of `self.circ`. A workaround was to do `self.circ = plaq_circuit.Circuit()` as the initialization step.

2023-09-27 11:27 UTC, antalszava commented on src/plaquette/device/_stimsim.py
> +    circ: plaq_circuit.Circuit | None,
This was an attempt to get around to the `src/plaquette/device/_stimsim.py:120: error: Incompatible types in assignment (expression has type "None", variable has type "Circuit")  [assignment]` issue from MyPy. It should be reverted. :+1:

2023-09-27 11:38 UTC, antalszava commented on src/plaquette/device/__init__.py
>          return self._backend.run(circuit, shots=shots)
That's a good idea, raising an error if `shots>1` for local simulators will notify the user right away. The current state only notes this in the docstring.

> (same goes for the after_reset parameter)

I'm not sure that ironing out the `after_reset` option is so straightforward. It is a feature that is basically only supported by `CircuitSimulator` (if it's turned on, it raises an error for `StimSimulator`). Frankly, I think it's an engineering burden to code up every new device in a way to raise an error for `after_reset=True` just because there is one simulator that uses it.

One alternative could be to allow `**backend_kwargs` to be passed in: this would allow:
* Passing `after_reset` only to `CircuitSimulator` if it's given by the user;
* The error mechanism for `after_reset=True` could be removed from `StimSimulator`;
* Having no extra burden on new backends that don't do anything with the `after_reset` argument.

2023-09-27 14:53 UTC, massarom commented on src/plaquette/device/_circuitsim.py
> +        self.circ = None
It's not a huge problem per sé, but definitely it's better not to add new code that goes against the code style in the docs. We can have a low-priority issue as a reminder, yes. I thought I got rid of all the other instances at some point, but I might be wrong.

2023-09-27 15:05 UTC, antalszava commented on src/plaquette/device/_circuitsim.py
> +        self.circ = None
Cool created an issue.

2023-09-27 15:23 UTC, massarom commented on src/plaquette/device/_stimsim.py
> +
> we do want to do that nonetheless, there's going to be a bit of a duplication between __init__ and reset, are we okay with that?

It's not a problem, because worse IMO is the additional mental overhead of having to realise that some variables appear in the class that you never saw in the init. It's not strictly repetition, because resetting is a legitimate operation: all variables are reset to a known state. Initialisation is different semantically, although practically they do basically the exact same things. Some more strict linters (e.g. I think Microsoft's Pyright) actually mark this as an error.

> Setting self.circ to None ends up bringing up an issue with MyPy

This is due to a wrong way of declaring the types of class variables. You *could* declare all your instance variables as class variables (lines 78-95), but this ends up being a mess and it should actually be removed. It was a spread convention in the codebase that was only bringing in troubles with type checkers and linters (as you also see), this in the `stim` simulator must have slipped through the cracks.

The solution is to declare instance variables *and their types* in a single spot: the `__init__`. For example, if you delete L84, mypy stops complaining about that (but starts complaining about other things). Usually fixing `mypy` complaints, even if it seems verbose, leads to less bugs, but of course it cannot become a dogma to follow. We should just use common sense, e.g. if fixing mypy complaints ends up adding 200 lines of code, maybe we can simply ignore some stuff, after careful checking.

2023-09-28 09:54 UTC, antalszava commented on src/plaquette/device/_stimsim.py
> +
> It's not a problem, because worse IMO is the additional mental overhead of having to realise that some variables appear in the class that you never saw in the init. It's not strictly repetition, because resetting is a legitimate operation: all variables are reset to a known state. Initialisation is different semantically, although practically they do basically the exact same things. Some more strict linters (e.g. I think Microsoft's Pyright) actually mark this as an error.

Oh, I see! Frankly, I've looked at this from a different angle where `__init__` and `reset` together are pretty small (hopefully) so it wouldn't bother the reader if something is only initialized in `reset`. Having said that, the suggestion is definitely more conventional and will likely benefit readability, so I've applied the changes.

> This is due to a wrong way of declaring the types of class variables. You could declare all your instance variables as class variables (lines 78-95), but this ends up being a mess and it should actually be removed. It was a spread convention in the codebase that was only bringing in troubles with type checkers and linters (as you also see), this in the stim simulator must have slipped through the cracks.

> The solution is to declare instance variables and their types in a single spot: the __init__. For example, if you delete L84, mypy stops complaining about that (but starts complaining about other things). Usually fixing mypy complaints, even if it seems verbose, leads to less bugs, but of course it cannot become a dogma to follow. We should just use common sense, e.g. if fixing mypy complaints ends up adding 200 lines of code, maybe we can simply ignore some stuff, after careful checking.

Oh wow, thanks for pointing that out! I've removed the declarations of the instance attributes on the class level and moved them into `__init__`. Also, I've changed to the preferred documentation of the attributes - although out of scope here - to make things simpler.

2023-09-28 11:00 UTC, antalszava commented
Thank you @massarom for the comments! I addressed them and now this is ready for another review.

2023-09-29 16:45 UTC, massarom commented on src/plaquette/device/__init__.py
>          return self._backend.run(circuit, shots=shots)
As far as I can see, if #47 gets merged this is not a problem anymore, since the error-tracker will supersede `CircuitSimulator`, no?

2023-09-29 21:23 UTC, massarom commented on src/plaquette/device/__init__.py
>          return self._backend.run(circuit, shots=shots)
> the error tracker uses CircuitSimulator, so that class will remain

Yes, but we don't need to stress about the API anymore, since it would become a "behind the scenes" step.

> https://github.com/qc-design/plaquette/pull/47 doesn't address the next step of making the error-tracker default.

I don't think that this additional step is worth an entire PR by itself, ***if*** making it default is no more work than mentioning it in the docs, also because right now there is no "default", the user still needs to make a conscious choice. We just need to mention a different argument for a `Device` backend.

2023-10-02 17:50 UTC, antalszava commented on src/plaquette/device/__init__.py
>          return self._backend.run(circuit, shots=shots)
> Yes, but we don't need to stress about the API anymore, since it would become a "behind the scenes" step.

The API that is being changed in this PR is already a "behind the scenes" step - it is not user-facing. This is an ironing out of the technical debt previously left in.  This PR makes the codebase cleaner and #47 introduces a new simulator. What is an open question at this point about going further with both?

> I don't think that this additional step is worth an entire PR by itself, if making it default is no more work than mentioning it in the docs, also because right now there is no "default", the user still needs to make a conscious choice. We just need to mention a different argument for a Device backend.

I'd be more comfortable with more functional testing from users when #47 has been merged and the related demonstration has also been merged and interested people have looked at it. In my perspective, the circuit simulator is one of the main points of contact a user interacts with in plaquette, so I think it's best to make it battle-tested as much as we can.

2023-10-03 09:51 UTC, massarom commented on src/plaquette/device/__init__.py
>          return self._backend.run(circuit, shots=shots)
> The API that is being changed in this PR is already a "behind the scenes" step - it is not user-facing

Sorry, what I meant is that when #47 gets merged, it will introduce a new simulator that (unless I lost something) it's going to be better than `CircuitSimulator` in all aspects, making the latter effectively useless for a user. If the user cannot select it, then there is no reason to have special treatment for it. Ideally, the creation of a reference frame can be done in a separate method of the new simulator, so that we don't need to drag around the old one anymore and at some point we can get rid of it.

The `**kwargs` solution should in any case fix all the problems in this point I think. The above it's just a comment for the future.

2023-10-05 06:05 UTC, massarom approved these changes

2023-10-05 06:07 UTC, merged