Add the error tracker backend
qc-design/plaquette pull request #47
Opened 2023-09-29 16:11 UTC by antalszava

2023-10-05 07:47 UTC, massarom requested changes
Mostly good, I just wanted to propose that the "frame operations" be moved to a submodule of `plaquette.pauli` so that they can be tested and used independently of the simulator itself if someone wants to. Right now to exploit them one *needs* to have a circuit and a simulator, but if I wanted to do some weird tests/calculations I would not be able to do that easily.

2023-10-05 07:47 UTC, massarom commented on src/plaquette/device/_errortrackingbackend.py
> +        if self.pauli_frame is not None:
We also need to check that the number of qubit indices given is an even number. Right now, if the number is odd, the process continues but would fail.

2023-10-05 07:47 UTC, massarom commented on src/plaquette/device/_errortrackingbackend.py
> +    def controlled_z(self, control: int, target: int):
Why does the controlled-X accept a sequence of pairs of indices, but here we only accept a single pair, and in separate arguments?

2023-10-05 07:47 UTC, massarom commented on src/plaquette/device/_errortrackingbackend.py
> +    def _pauli_apply_sample(self, sample: int, qubit: int):
This needs a better name, and a docstring.

"Sample", everywhere else in the codebase, is used to refer to a measurement sample resulting from a simulation, but here it's an operator?

I think something like this is done in `CircuitSimulator`, but even there it's a bad naming choice. I would take the opportunity here to choose something more descriptive.

2023-10-05 07:47 UTC, massarom commented on tests/unittests/device/error_tracker_test.py
> +    return params_list
These functions are somewhere else in the tests. It might be worth it to combine them into a common set of test fixtures somewhere in a pytest configuration file.

2023-10-05 09:02 UTC, antalszava commented
@massarom thank you for the comments! :pray: 

> Mostly good, I just wanted to propose that the "frame operations" be moved to a submodule of plaquette.pauli so that they can be tested and used independently of the simulator itself if someone wants to. Right now to exploit them one needs to have a circuit and a simulator, but if I wanted to do some weird tests/calculations I would not be able to do that easily.

Does "frame operations" refer to the logic that is implemented in the methods of the ErrorTrackingBackend that update the Pauli frame by applying a Clifford/error channel/measurement? I.e., mostly those that are being called in the `_handle_gate` internal method. I'd picture that solution to be made functional in a way that the main input to a function in the proposed `plaquette.pauli` submodule would be the Pauli frame, the function transforms the Pauli frame and returns the new updated Pauli frame. Is that what we'd have in mind here?

2023-10-05 09:11 UTC, massarom commented
Yes, sorry for the lack of clarity.

We can define a new type alias and set as the first argument to any functions we move in the new module, exactly how `plaquette.pauli` does things. Each function gets the frame as the first argument and then any other additional argument necessary for that specific function.

2023-10-05 09:34 UTC, antalszava commented on src/plaquette/device/_errortrackingbackend.py
> +        if self.pauli_frame is not None:
Good idea, updated this :+1:

2023-10-05 09:34 UTC, antalszava commented on src/plaquette/device/_errortrackingbackend.py
> +    def controlled_z(self, control: int, target: int):
Good catch, updated. Thanks!

2023-10-05 09:46 UTC, antalszava commented on src/plaquette/device/_errortrackingbackend.py
> +    def _pauli_apply_sample(self, sample: int, qubit: int):
Agreed. Not sure about a great name that's completely different to the quantum sample, as we're sampling here too. So went with `_apply_pauli_from_int_sample` and added the docstring, but let me know if there's a better name.

2023-10-05 10:24 UTC, massarom commented on src/plaquette/device/_errortrackingbackend.py
> +    def _pauli_apply_sample(self, sample: int, qubit: int):
Does the choice of Pauli operator need to come from outside (i.e. as argument)? Because if not, we can just call this `_apply_random_pauli` or something similar and it's clear what it means.

2023-10-05 15:47 UTC, antalszava commented on tests/unittests/device/error_tracker_test.py
> +    return params_list
Good idea, moved them to `conftest.py` :+1:

2023-10-05 16:06 UTC, antalszava commented on src/plaquette/device/_errortrackingbackend.py
> +    def _pauli_apply_sample(self, sample: int, qubit: int):
Yes, because there are at least 2 potential ways choosing may be done before using this machinery:
1. Single qubit Pauli op: 4 distinct probabilities inputted by the user;
2. Two-qubit Pauli op: 16 distinct probabilities inputted by the user.

Case 2. could be transformed into case 1., but I don't think it's worth complicating the logic just use one to two fewer functions.

2023-10-05 16:09 UTC, antalszava commented on .pre-commit-config.yaml
> +           - types-pyyaml
Upon moving commonly used functions to conftest, this update was required to run mypy.

2023-10-05 16:10 UTC, antalszava commented
> Yes, sorry for the lack of clarity.

We can define a new type alias and set as the first argument to any functions we move in the new module, exactly how plaquette.pauli does things. Each function gets the frame as the first argument and then any other additional argument necessary for that specific function.

Np, thank you! Sure, I've created a `src/plaquette/pauli_frame.py` and moved machinery there.

In addition, this should be good for another review now. :+1:

2023-10-09 07:46 UTC, massarom requested changes

2023-10-09 07:46 UTC, massarom commented on src/plaquette/device/_errortrackingbackend.py
> +                self.any_error_applied = self.apply_branch = plaquette.rng.random() < p
I think this links the two variables together, such that if one gets changed, the other is changed too. Is this the behaviour you want?

If you only want to give the same value to two variable, you need to do that explicitely.

2023-10-09 07:46 UTC, massarom commented on src/plaquette/pauli_frame.py
> +def cx(
```suggestion
def controlled_not_gate(
```

This and the following changes are for consistency with how the pauli module is written.

2023-10-09 07:46 UTC, massarom commented on src/plaquette/pauli_frame.py
> +
```suggestion


cx = controlled_not_gate

```

2023-10-09 07:46 UTC, massarom commented on src/plaquette/pauli_frame.py
> +def cz(
```suggestion
def controlled_phase_gate(
```

2023-10-09 07:46 UTC, massarom commented on src/plaquette/pauli_frame.py
> +
```suggestion

cz = controlled_phase_gate

```

2023-10-09 08:58 UTC, antalszava commented on src/plaquette/device/_errortrackingbackend.py
> +                self.any_error_applied = self.apply_branch = plaquette.rng.random() < p
Not sure that's the working for a bool object, I think that may be the behaviour if we had some reference-like object.

See here:

![image](https://github.com/qc-design/plaquette/assets/24476053/ccd79199-d813-4930-91ca-614d241115b6)

2023-10-09 17:04 UTC, massarom approved these changes

2023-10-09 17:06 UTC, merged