Draft: Branch to cleanup ssc/api ready for merge.
qc-design/plaquette pull request #70
Opened 2023-10-25 17:35 UTC by isolatedinformation

This message body will be used to track all the small changes made, since there will be quite a few.
- Suppress PyMatching and inaccesible file warnings when running the simulations.
- Fix incorrectly generated stabilizers of the rectangular versions of the rotated planar code. 
- Make MeasurementSample use the weight of the logical operator instead of code distance and support multiple logical operator measurements. 

Update: 25-10-2023 19:30, after all these changes I ran the previously obtained threshold plots for the rotated planar code, and they are giving the right thresholds. The rectangular codes however are not being processed currently. I will post more updates in the next update.

2023-10-26 13:50 UTC, antalszava commented
Hi @isolatedinformation, I know that this PR is in work in progress, but I've come across a failure and thought of mentioning it as FYI. Running `examples/ler_decreases.py` seems to fail with:

```py
Traceback (most recent call last):
  File "/plaquette/examples/ler_decreases.py", line 66, in <module>
    results = MeasurementSample.from_code_and_raw_results(ssc, raw, erasure, num_rounds)
  File "/plaquette/src/plaquette/device/__init__.py", line 115, in from_code_and_raw_results
    logop_wts = [code.distances[j] for j in logop_idxs]
  File "/plaquette/src/plaquette/device/__init__.py", line 115, in <listcomp>
    logop_wts = [code.distances[j] for j in logop_idxs]
IndexError: index 2 is out of bounds for axis 0 with size 2
```

2023-10-26 14:42 UTC, isolatedinformation commented
Thanks for the report. Yes, there is a bug because the signature of the changed. You now also have to give the logical_ops we have measured to process the measurement sample.

2023-10-26 15:34 UTC, isolatedinformation commented on requirements.txt
> +igraph
Nope, those dependencies were removed everywhere from the code. icecream is just a nice command line debugging tool.

2023-10-29 11:57 UTC, massarom requested changes
Besides the line-level comments, any reason why this

```
FAILED tests/integrationtests/generator_test.py::TestQECCircuitGenerator::test_generated_syndrome - IndexError: index 2 is out of bounds for axis 0 with size 2
```

fails? The other failing tests should be fixed in the docs branch, but this one is weird.

2023-10-29 11:57 UTC, massarom commented on src/plaquette/codes/utils.py
If the functions in this module are utilities *for the developers*, then the entire module should be private `utils.py -> _utils.py` and the functions inside can be normal. I think mypy or some other type checkers complains about using private functions in a public module.

2023-10-29 11:57 UTC, massarom commented on src/plaquette/decoders/__init__.py
> +                    edges_weights.append(-(2**24) + 1)
Why not `float('inf')`? Only the specific decoder wrappers should care about precise values.

2023-10-29 11:57 UTC, massarom commented on src/plaquette/decoders/__init__.py
> +                        edges_weights.append(-np.log(p / (1 - p)))
Why these are not treated the same as in-plane edges?

2023-10-29 11:57 UTC, massarom commented on src/plaquette/device/__init__.py
> +        # ic(logop_wts)
I'm sorry, but these two comments are too cryptic. Can you expand the acronyms?

2023-10-29 11:57 UTC, massarom commented on src/plaquette/errors/common_models.py
> +        code: The `Code` object to define errors for.
```suggestion
        code: the :class:`.Code` object to define errors for.
```

2023-10-29 11:57 UTC, massarom commented on tests/test_regression_ler_decrease.py
> -            decoders.UnionFindDecoder,
No need to parametrise a variable that only ever has one parameter. (applies also to below)

2023-10-30 05:09 UTC, massarom approved these changes
Good as long as the tests pass

2023-10-30 07:07 UTC, merged