Updating figures in the tutorials
qc-design/plaquette pull request #79
Opened 2023-11-05 19:41 UTC by diazlcarlos98

In this branch I have been updating the first and second tutorials so that the `Visualizer` class' functions are being called properly, as well as replacing the old figures with new ones. Additionally, given that qubit and ancilla indices have changed, I have been carefully checking that the references to these indices in the text actually correspond to the ones in the visualization.

2023-11-10 13:51 UTC, massarom requested changes
@diazlcarlos98 thanks a lot for this! Can you confirm that if you install `plaquette-graph` from master that tests that is currently failing in the Actions would pass?

2023-11-10 13:51 UTC, massarom commented on docs/qec_tutorials/decoding/decoding.rst
> +We first visualize the $ X $ error probability distribution:
Are you sure this is the correct marker for in-line math? Everywhere else `:math:` is used.

2023-11-11 18:13 UTC, diazlcarlos98 commented
I tried but it did nothing. I don't think that my local installation of `plaquette-graph` would have anything to do with how Git is running the tests. By reading a little bit on the error details, I guess the error would be that somewhere in the C++ binding file, the weights are being passed as a numpy array, instead of the required list of floats.

2023-11-13 17:00 UTC, massarom commented
>  I don't think that my local installation of plaquette-graph would have anything to do with how Git is running the tests.

The point is that if _you_ have `graph` installed from its `master` branch and the tests run, this tells us that the problems in the tests is only that the GH Actions are using an old version of `plaquette-graph`. The binding error you see is because the C++ implementation of UF is compiled against a different binary version of `plaquette-graph`, which is not the one on PyPI (from where currently the tests take `plaquette-graph`).

> I tried but it did nothing

Meaning that locally all the tests pass?

2023-11-13 18:09 UTC, diazlcarlos98 commented
> The point is that if you have graph installed from its master branch and the tests run, this tells us that the problems in the tests is only that the GH Actions are using an old version of plaquette-graph.

Apologies. Yes, that makes sense.

> Meaning that locally all the tests pass?

I just tried running the .py file that was failing (tests/unittests/test_decoders.py) and all of them passed!

2023-11-15 09:27 UTC, massarom commented
@diazlcarlos98 there was a fix in the base branch that likely impacts your work here. Can you double-check that all still is consistent after merging the base branch in this PR?

2023-11-16 10:58 UTC, diazlcarlos98 commented
I'll have to re-do a couple of pictures because of the -previously- missing $Y$ correction in the visualizer.

2023-11-17 17:53 UTC, massarom approved these changes
Thank you @diazlcarlos98! Awesome job!

2023-11-22 08:13 UTC, merged