IBM plugin tutorial
qc-design/plaquette pull request #95
Opened 2023-12-04 17:00 UTC by antalszava

2023-12-08 14:51 UTC, massarom requested changes
Content-wise is very good, I left some formatting-related comments and a note about the behaviour of a function.

2023-12-08 14:51 UTC, massarom commented on docs/advanced/ibm_plugin/index.rst
> +Detection event fractions
A simple explanation of what these things are would help, even in the introduction where they are first mentioned.

2023-12-08 14:51 UTC, massarom commented on docs/advanced/ibm_plugin/index.rst
> +        ler = decode_given_samples(samples, system_name, code, n_qubits, n_rounds, reps, file_dir=file_dir, want_det_event_fraction=True)
I'm a bit confused here, although my doubts stem from just reading the code without running anything.

Unless `file_dir` is an _absolute_ path, this function fill change to an always-deeper folder at each loop iteration, AFAICS.

1. iteration: `file_dir`
2. iteration: `file_dir/file_dir`
3. etc.

because `decode_given_samples` always calls `os.chdir` without ever going back to the original one. Either "go back" once the function is done, or convert the path to an absolute one before changing. Even better would be to use the [`pathlib`](https://docs.python.org/3/library/pathlib.html) standard Python library for anything related to paths.

2023-12-08 14:51 UTC, massarom commented on docs/advanced/ibm_plugin/index.rst
> +to plaquette and IBM quantum!
```suggestion
to ``plaquette`` and IBM quantum!
```

2023-12-08 14:51 UTC, massarom commented on docs/advanced/ibm_plugin/index.rst
> +        pip install git+https://github.com/qc-design/plaquette-ibm-backend/tree/rep_delay
```suggestion
```

We can remove this now because that branch is going to be merged very soon.

2023-12-11 09:37 UTC, antalszava commented on docs/advanced/ibm_plugin/index.rst
> +Experience service. At the time of writing, this means that one can run quantum
I'd leave it out because links break relatively quickly and we'll need to update them ourselves manually basically quarterly/every half a year. It may not sound like much but gives a not-so-great impression and creates the broken window effect. Overall, I think readers will find what they're looking for easily.

2023-12-11 09:40 UTC, antalszava commented on docs/advanced/ibm_plugin/index.rst
> +        ler = decode_given_samples(samples, system_name, code, n_qubits, n_rounds, reps, file_dir=file_dir, want_det_event_fraction=True)
`file_dir` is an absolute path. I'll add this to its description. I wouldn't change the code too much because it works if `file_dir` is an absolute path.

2023-12-11 09:56 UTC, antalszava commented on docs/advanced/ibm_plugin/index.rst
> +subsamples.
Updated. :+1:

2023-12-11 15:49 UTC, antalszava commented
The tutorial has been migrated to the [PR in the plugin repo](https://github.com/qc-design/plaquette/pull/95).

2023-12-11 15:49 UTC, closed without merging